server:
  address: 0.0.0.0:7777
  model: debug 

db:
  db-driver: postgres
  host: 127.0.0.1
  port: 5431
  db: e_commerce
  username: root
  password: secret
  charset: utf8
  max-idle-conns: 10
  max-open-conns: 100

mylog:
  path: ./log
  name: sys
  model: file
  format: console
  level: debug

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

jwt-token:
  issuer: user
  signing-key: mysecret
  access-token-duration: 3h
  refresh-token-duration: 24h
  blacklist_grace_period: 10m
