// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID int64 `json:"id"`
}

type CartItem struct {
	ID        int64 `json:"id"`
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
	Count     int64 `json:"count"`
}

type Comment struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	Content   string    `json:"content"`
	Status    int16     `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID          uuid.UUID `json:"id"`
	UserID      int64     `json:"user_id"`
	TotalAmount string    `json:"total_amount"`
	TotalCount  int64     `json:"total_count"`
	IsPaied     bool      `json:"is_paied"`
	CreatedAt   time.Time `json:"created_at"`
}

type OrderItem struct {
	ID        int64     `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	Count     int64     `json:"count"`
	ProductID int64     `json:"product_id"`
}

type Product struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	CategoryID  int64     `json:"category_id"`
	Image       string    `json:"image"`
	Stock       int64     `json:"stock"`
	Sell        int64     `json:"sell"`
	Price       string    `json:"price"`
	OnSell      string    `json:"on_sell"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProductCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Sort int32  `json:"sort"`
}

type ProductRate struct {
	ID        int64         `json:"id"`
	UserID    sql.NullInt64 `json:"user_id"`
	ProductID sql.NullInt64 `json:"product_id"`
	Rate      int16         `json:"rate"`
}

type Seller struct {
	ID          int64  `json:"id"`
	SellerName  string `json:"seller_name"`
	BankAccount string `json:"bank_account"`
}

type SellerRate struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	Rate   int16 `json:"rate"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	Ip           string    `json:"ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiredAt    time.Time `json:"expired_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int64         `json:"id"`
	UserName          string        `json:"user_name"`
	HashedPassword    string        `json:"hashed_password"`
	Email             string        `json:"email"`
	FullName          string        `json:"full_name"`
	Gender            sql.NullInt16 `json:"gender"`
	UserRank          int32         `json:"user_rank"`
	CreatedAt         time.Time     `json:"created_at"`
	ChangedPasswordAt time.Time     `json:"changed_password_at"`
}

type UserDeliver struct {
	ID      int64  `json:"id"`
	UserID  int64  `json:"user_id"`
	Address string `json:"address"`
}
