// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCart(ctx context.Context, id int64) (int64, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateProductRate(ctx context.Context, arg CreateProductRateParams) (ProductRate, error)
	CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error)
	CreateSellerRate(ctx context.Context, arg CreateSellerRateParams) (SellerRate, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserDeliver(ctx context.Context, arg CreateUserDeliverParams) (UserDeliver, error)
	DeleteCart(ctx context.Context, id int64) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteComment(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeleteOrderItem(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductCategory(ctx context.Context, id int64) error
	DeleteProductRate(ctx context.Context, id int64) error
	DeleteSeller(ctx context.Context, id int64) error
	DeleteSellerRate(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserDeliver(ctx context.Context, id int64) error
	GetCommentByProductId(ctx context.Context, productID int64) (Comment, error)
	GetCommentByUserId(ctx context.Context, userID int64) (Comment, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItemByOrderId(ctx context.Context, orderID uuid.UUID) (OrderItem, error)
	GetOrderItemByProductId(ctx context.Context, productID int64) ([]OrderItem, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductCategory(ctx context.Context, id int64) (ProductCategory, error)
	GetProductRateByProductId(ctx context.Context, productID sql.NullInt64) (ProductRate, error)
	GetProductRateByUserId(ctx context.Context, userID sql.NullInt64) (ProductRate, error)
	GetSeller(ctx context.Context, id int64) (Seller, error)
	GetSellerRateByUserId(ctx context.Context, userID int64) (SellerRate, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserDeliver(ctx context.Context, id int64) (UserDeliver, error)
	ListAllProductCategory(ctx context.Context) ([]ProductCategory, error)
	ListCartItem(ctx context.Context, cartID int64) ([]ListCartItemRow, error)
	ListProduct(ctx context.Context, arg ListProductParams) ([]Product, error)
	ListProductByType(ctx context.Context, arg ListProductByTypeParams) ([]Product, error)
	ListProductCategory(ctx context.Context, categoryID int64) ([]ProductCategory, error)
	ListUserDeliverByUserId(ctx context.Context, userID int64) ([]UserDeliver, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) error
	UpdateOrderInfo(ctx context.Context, arg UpdateOrderInfoParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateProductRateByUserId(ctx context.Context, arg UpdateProductRateByUserIdParams) (ProductRate, error)
	UpdateProductStockSell(ctx context.Context, arg UpdateProductStockSellParams) (Product, error)
	UpdateSellerRate(ctx context.Context, arg UpdateSellerRateParams) (SellerRate, error)
	UpdateUserDeliver(ctx context.Context, arg UpdateUserDeliverParams) (UserDeliver, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
